---
- name: Setup Coffee Project Environment
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    # https://medium.com/codex/how-to-install-docker-using-ansible-84d40005169
    # https://docs.docker.com/engine/install/ubuntu/
    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Jammy is 22.04 release
    - name: Add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker Packages
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
    
    # https://stackoverflow.com/questions/42040688/docker-daemon-start-using-ansible
    - name: Start docker daemon
      service:
        name: docker
        state: started

    - name: Expose port 80 with iptables
      shell: 
        "sudo iptables -I INPUT -p tcp -m tcp --dport 80 -j ACCEPT"

    - name: Copy environment files
      copy:
        src: environment-files/Dockerfile
        dest: /home/ashon/